apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  annotations:
    backstage.io/kubernetes-id: my-cluster
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: 'app=mydata'
  description: Searcher
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
