apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  annotations:
    backstage.io/kubernetes-id: test-cluster
    'backstage.io/kubernetes-namespace': default
  description: Searcher
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
